# Generated by Django 3.0.5 on 2020-04-19 17:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_auto_20200303_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('messege', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
